-   id: check-absent-migrations
    name: Check absent migrations with manage.py makemigrations --check --dry-run
    entry: check-absent-migrations
    pass_filenames: false
    language: system
    always_run: true