-   id: makemigrations-check-absent
    name: "Check absent migrations with manage.py makemigrations --check --dry-run"
    entry: makemigrations-check-absent
    pass_filenames: false
    language: python
    always_run: true