-   id: makemigrations-check-absent
    name: "Check absent migrations with manage.py makemigrations --check --dry-run"
    # entry: makemigrations-check-absent
    entry: python hooks/makemigrations_check_absent.py
    pass_filenames: false
    language: system
    always_run: true