name: pre-commit-hooks-django-migrations CI

on:
  push:
    branches: [main, develop]
    tags:
      - "*"
  pull_request:
    branches: [ main ]

jobs:
  read-the-docs:
    if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}

  build-n-publish:
    if: startsWith(github.ref, 'refs/tags')
    name: "Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI"
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@master
      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: "Install pypa/build"
        run: |
          python -m pip install build --user
      - name: "Build a binary wheel and a source tarball"
        run: |
          python -m build --sdist --wheel --outdir dist/ .
      - name: "Publish distribution 📦 to Test PyPI"
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}