name: pre-commit-hooks-django-migrations CI

on:
  push:
    branches: [main, develop]
    tags:
      - "*"
  pull_request:
    branches: [ main ]

jobs:
  read-the-docs:
    if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}